# Global Settings
project:
  name: "Quantitative Finance Framework"
  version: "0.1.0"
  environment: "development"  # development, testing, production

# Data Sources
data_sources:
  yahoo_finance:
    enabled: true
    cache_dir: "data/cache"
    update_frequency: "1d"
  
  alternative_data:
    twitter:
      enabled: true
      api_key: "${TWITTER_API_KEY}"
      max_tweets: 1000
      update_frequency: "1h"
    
    sec_edgar:
      enabled: true
      user_agent: "Your Company Name"
      cache_dir: "data/sec_filings"
    
    github:
      enabled: true
      api_key: "${GITHUB_API_KEY}"
      update_frequency: "1d"

# Model Settings
models:
  reinforcement_learning:
    enabled: true
    algorithms:
      - name: "PPO"
        params:
          learning_rate: 0.0003
          n_steps: 2048
          batch_size: 64
      - name: "DDPG"
        params:
          learning_rate: 0.0001
          buffer_size: 1000000
      - name: "A2C"
        params:
          learning_rate: 0.0007
          n_steps: 5
    
    environment:
      trading_fee: 0.001
      slippage: 0.0001
      initial_balance: 100000
  
  deep_learning:
    enabled: true
    models:
      - name: "LSTM"
        params:
          units: [64, 32]
          dropout: 0.2
          recurrent_dropout: 0.2
      - name: "Transformer"
        params:
          num_heads: 8
          num_layers: 4
          dropout: 0.1
      - name: "GRU"
        params:
          units: [128, 64]
          dropout: 0.2
  
  supervised_learning:
    enabled: true
    models:
      - name: "RandomForest"
        params:
          n_estimators: 100
          max_depth: 10
      - name: "XGBoost"
        params:
          learning_rate: 0.1
          max_depth: 6
      - name: "LightGBM"
        params:
          learning_rate: 0.05
          num_leaves: 31

# Feature Engineering
feature_engineering:
  technical_indicators:
    enabled: true
    indicators:
      - name: "RSI"
        params:
          period: 14
      - name: "MACD"
        params:
          fast_period: 12
          slow_period: 26
      - name: "BollingerBands"
        params:
          period: 20
          std_dev: 2
  
  statistical_features:
    enabled: true
    features:
      - name: "returns"
        params:
          periods: [1, 5, 10, 20]
      - name: "volatility"
        params:
          window: 20
      - name: "momentum"
        params:
          periods: [5, 10, 20]

# Backtesting
backtesting:
  enabled: true
  settings:
    initial_capital: 100000
    commission: 0.001
    slippage: 0.0001
    position_sizing:
      method: "fixed"  # fixed, kelly, optimal
      size: 0.1  # 10% of portfolio per trade

# NLP Processing
nlp:
  enabled: true
  models:
    sentiment:
      - name: "VADER"
        params:
          threshold: 0.05
      - name: "FinBERT"
        params:
          model_name: "ProsusAI/finbert"
    
    topic_modeling:
      - name: "LDA"
        params:
          num_topics: 10
      - name: "BERTopic"
        params:
          min_topic_size: 10

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/quant_framework.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# API Settings
api:
  enabled: true
  host: "0.0.0.0"
  port: 8000
  debug: true
  cors_origins: ["*"]
  rate_limit: 100  # requests per minute 